# Generated by Django 2.1.7 on 2019-04-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=200)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=200)),
                ('tag_type', models.IntegerField(choices=[(0, 'Topic'), (1, 'Tech'), (2, 'Event')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='community_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='homepage_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Commenting'), (1, 'Bootstrapping'), (2, 'Prototyping'), (3, 'Testing'), (4, 'Maintaining'), (5, 'Drifting'), (6, 'Hibernating')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='project.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='project.Tag'),
        ),
    ]
